-- Insert all 50 quiz questions into the database
-- First, clear existing questions to avoid duplicates
DELETE FROM quiz_questions;

-- Multiple Choice Questions (40 questions) - All have the same column structure
INSERT INTO quiz_questions (id, question, options, correct_answer, category, type, difficulty) VALUES
(1, 'Which of the following best describes an "ownership mentality"?', '["Doing only what your manager tells you", "Taking initiative and acting in the best interest of the business", "Avoiding risks and waiting for clear instructions", "Delegating all responsibilities to others"]', 'Taking initiative and acting in the best interest of the business', 'Leadership', 'multiple_choice', 'medium'),
(2, 'You notice vendor payments are delayed. What is your FIRST step?', '["Escalate to senior leadership immediately", "Ignore it, since it happens often", "Check accounting records and communicate with vendors", "Wait for the vendor to complain"]', 'Check accounting records and communicate with vendors', 'Operations', 'multiple_choice', 'medium'),
(3, 'Which is the MOST important reason for SOPs (Standard Operating Procedures)?', '["To reduce creativity", "To ensure consistency and efficiency", "To increase paperwork", "To replace training"]', 'To ensure consistency and efficiency', 'Operations', 'multiple_choice', 'easy'),
(4, 'Which of these is a key benefit of Zoho CRM?', '["It automatically files taxes", "It manages customer relationships and sales pipelines", "It generates electricity", "It replaces accountants"]', 'It manages customer relationships and sales pipelines', 'Technology', 'multiple_choice', 'easy'),
(5, 'A US client sends an urgent email at midnight IST. What do you do?', '["Reply immediately, since you must always be online", "Wait until your shift starts, then respond", "Acknowledge quickly if critical, otherwise schedule for working hours", "Ignore it"]', 'Acknowledge quickly if critical, otherwise schedule for working hours', 'Communication', 'multiple_choice', 'medium'),
(6, 'Which quality is LEAST important for this role?', '["Strong communication skills", "Hunger for growth", "Consistent follow-through", "Desire to work alone with no accountability"]', 'Desire to work alone with no accountability', 'Leadership', 'multiple_choice', 'easy'),
(7, 'The phrase "act like an entrepreneur" in the job description implies:', '["Avoiding risks at all costs", "Taking ownership, solving problems, and innovating", "Working fewer hours for more money", "Doing tasks only when asked"]', 'Taking ownership, solving problems, and innovating', 'Leadership', 'multiple_choice', 'medium'),
(8, 'A customer leaves a 1-star review on Google. What''s the BEST response?', '["Delete it", "Respond politely, acknowledge the issue, and offer resolution", "Argue with the customer publicly", "Ignore it"]', 'Respond politely, acknowledge the issue, and offer resolution', 'Customer Service', 'multiple_choice', 'medium'),
(9, 'Which of these is a creative problem-solving example?', '["Copying a competitor''s approach exactly", "Stopping operations until someone else solves it", "Designing a new workflow to reduce errors", "Avoiding new solutions"]', 'Designing a new workflow to reduce errors', 'Problem Solving', 'multiple_choice', 'medium'),
(10, 'If a sales rep misses their target, you should:', '["Fire them immediately", "Provide feedback, training, and set clear expectations", "Ignore it", "Reduce their salary"]', 'Provide feedback, training, and set clear expectations', 'Management', 'multiple_choice', 'medium'),
(11, '"Hungry and aggressive for growth" suggests:', '["Always being dissatisfied", "Taking initiative and pushing for improvement", "Being rude to clients", "Cutting corners"]', 'Taking initiative and pushing for improvement', 'Leadership', 'multiple_choice', 'medium'),
(12, 'Which report is MOST important for compliance?', '["Fashion trends", "Financial statements and tax filings", "Daily memes", "Random customer emails"]', 'Financial statements and tax filings', 'Compliance', 'multiple_choice', 'easy'),
(13, 'Which of these would NOT be part of digital marketing?', '["Google Ads", "SEO optimization", "Instagram campaigns", "Preparing financial statements"]', 'Preparing financial statements', 'Marketing', 'multiple_choice', 'easy'),
(14, 'Which is an example of agency at work?', '["Waiting for a manager to assign tasks", "Identifying a broken process and fixing it proactively", "Avoiding accountability for mistakes", "Following instructions blindly"]', 'Identifying a broken process and fixing it proactively', 'Leadership', 'multiple_choice', 'medium'),
(15, 'In sales strategy, "lead conversion rate" means:', '["Percentage of website visitors", "Percentage of leads turned into paying customers", "Total number of cold calls", "Marketing spend per campaign"]', 'Percentage of leads turned into paying customers', 'Sales', 'multiple_choice', 'medium'),
(16, 'Which is an example of poor written English?', '["Dear Sir, I will complete this by tomorrow.", "Hey boss, u no worry, I finish lol.", "I will ensure this is done on priority.", "Attached is the requested file for your review."]', 'Hey boss, u no worry, I finish lol.', 'Communication', 'multiple_choice', 'easy'),
(17, 'A US customer uses slang you don''t understand. What do you do?', '["Pretend you understand", "Politely ask for clarification", "Ignore it", "End the conversation"]', 'Politely ask for clarification', 'Communication', 'multiple_choice', 'easy'),
(18, 'Which is the most measurable KPI for marketing?', '["Creativity of campaign", "Click-through rate", "Employee mood", "Logo color"]', 'Click-through rate', 'Marketing', 'multiple_choice', 'medium'),
(19, 'You are asked to cut costs by 10%. What''s your BEST approach?', '["Reduce critical staff immediately", "Analyze expenses, prioritize cuts with least impact on growth", "Cancel all marketing", "Stop paying vendors"]', 'Analyze expenses, prioritize cuts with least impact on growth', 'Financial Management', 'multiple_choice', 'hard'),
(20, 'Which leadership style works best for scaling teams?', '["Micromanagement", "Autocratic control", "Coaching and empowerment", "Avoiding involvement"]', 'Coaching and empowerment', 'Leadership', 'multiple_choice', 'medium'),
(21, 'What is the opposite of accountability?', '["Ownership", "Transparency", "Blame-shifting", "Responsibility"]', 'Blame-shifting', 'Leadership', 'multiple_choice', 'easy'),
(22, 'IQ-style: If all entrepreneurs are leaders, and some leaders are employees, then:', '["All entrepreneurs are employees", "Some entrepreneurs may be employees", "No entrepreneur is an employee", "Entrepreneurs cannot be leaders"]', 'Some entrepreneurs may be employees', 'Logic', 'multiple_choice', 'hard'),
(23, 'If 5 workers complete a project in 10 days, how many days will 10 workers take (assuming equal productivity)?', '["5 days", "10 days", "20 days", "2 days"]', '5 days', 'Math', 'multiple_choice', 'medium'),
(24, 'Which tax is typically required in India for businesses?', '["GST", "Property tax only", "Road tax only", "Import duty only"]', 'GST', 'Business', 'multiple_choice', 'easy'),
(25, 'Which option is the BEST example of proactive communication?', '["Waiting until asked for updates", "Sending regular progress reports before being asked", "Avoiding tough conversations", "Replying late"]', 'Sending regular progress reports before being asked', 'Communication', 'multiple_choice', 'medium'),
(26, 'Which US holiday often affects business operations in November?', '["Diwali", "Thanksgiving", "Holi", "Ramadan"]', 'Thanksgiving', 'Business', 'multiple_choice', 'easy'),
(27, 'Which of these is a CRM tool?', '["Photoshop", "Zoho", "AutoCAD", "Canva"]', 'Zoho', 'Technology', 'multiple_choice', 'easy'),
(28, 'What is the plural of "criterion"?', '["Criterions", "Criteria", "Criterias", "Criterion"]', 'Criteria', 'English', 'multiple_choice', 'medium'),
(29, 'Which of these is MOST important for customer loyalty?', '["Fast responses and consistent service", "Expensive marketing", "Frequent discounts only", "Aggressive sales tactics"]', 'Fast responses and consistent service', 'Customer Service', 'multiple_choice', 'medium'),
(30, 'If sales revenue is ₹10,00,000 and costs are ₹7,50,000, what is profit?', '["₹2,50,000", "₹7,50,000", "₹10,00,000", "₹17,50,000"]', '₹2,50,000', 'Math', 'multiple_choice', 'easy'),
(31, 'Which is a strong interview question to test ownership?', '["How many siblings do you have?", "Describe a time when you fixed a problem without being asked.", "What is your favorite movie?", "What is 2 + 2?"]', 'Describe a time when you fixed a problem without being asked.', 'HR', 'multiple_choice', 'medium'),
(32, 'Which is the most effective sales follow-up?', '["One generic email sent once", "A personalized sequence of emails and calls", "No follow-up", "Waiting for client to reply"]', 'A personalized sequence of emails and calls', 'Sales', 'multiple_choice', 'medium'),
(33, 'What''s the BEST way to scale sales quickly?', '["Hire more salespeople without training", "Build repeatable processes and train effectively", "Cut marketing budget", "Sell to anyone without targeting"]', 'Build repeatable processes and train effectively', 'Sales', 'multiple_choice', 'medium'),
(34, 'Which of the following is NOT a key characteristic of an ownership mentality?', '["Taking responsibility for outcomes", "Blaming others for failures", "Proactively solving problems", "Thinking long-term"]', 'Blaming others for failures', 'Leadership', 'multiple_choice', 'easy'),
(35, 'When managing vendor relationships, which approach is most effective?', '["Always negotiating for the lowest price", "Building long-term partnerships with reliable vendors", "Switching vendors frequently to keep them competitive", "Avoiding communication unless there''s a problem"]', 'Building long-term partnerships with reliable vendors', 'Vendor Management', 'multiple_choice', 'medium'),
(36, 'What is the primary purpose of a sales pipeline?', '["To track marketing expenses", "To manage and track potential customers through the sales process", "To store customer contact information", "To generate invoices"]', 'To manage and track potential customers through the sales process', 'Sales', 'multiple_choice', 'medium'),
(37, 'Which of these is the best approach to handling customer complaints?', '["Ignoring them until they go away", "Listening actively, acknowledging the issue, and providing solutions", "Defending the company''s position immediately", "Transferring them to someone else"]', 'Listening actively, acknowledging the issue, and providing solutions', 'Customer Service', 'multiple_choice', 'medium'),
(38, 'What is the most effective way to measure team performance?', '["Only tracking individual metrics", "Using a combination of quantitative and qualitative measures", "Relying solely on customer feedback", "Comparing to industry averages only"]', 'Using a combination of quantitative and qualitative measures', 'Performance Management', 'multiple_choice', 'medium'),
(39, 'Which approach is best for handling conflicting priorities?', '["Always choosing the most urgent task", "Evaluating impact and aligning with business goals", "Doing whatever the boss asks for first", "Avoiding difficult decisions"]', 'Evaluating impact and aligning with business goals', 'Decision Making', 'multiple_choice', 'medium'),
(40, 'Which of these best demonstrates strategic thinking?', '["Focusing only on immediate tasks", "Considering long-term implications and planning accordingly", "Following established procedures without question", "Avoiding any risks or changes"]', 'Considering long-term implications and planning accordingly', 'Strategic Thinking', 'multiple_choice', 'hard');

-- Short Answer Questions (8 questions) - Different column structure (no options, no correct_answer)
INSERT INTO quiz_questions (id, question, category, type, max_length) VALUES
(41, 'Describe a time you took initiative without being told. What was the outcome?', 'Leadership', 'short_answer', 200),
(42, 'How would you explain "ownership mentality" to a new team member?', 'Leadership', 'short_answer', 200),
(43, 'Write a professional 2-sentence reply to a client who is upset about late delivery.', 'Communication', 'short_answer', 200),
(44, 'Suggest one improvement you would make to a sales funnel for faster conversions.', 'Sales', 'short_answer', 200),
(45, 'How do you balance speed vs. quality in business operations?', 'Operations', 'short_answer', 200),
(46, 'What daily habits help you stay accountable?', 'Leadership', 'short_answer', 200),
(47, 'If given ₹1,00,000 budget for digital marketing, how would you allocate it?', 'Marketing', 'short_answer', 200),
(48, 'In one paragraph, describe how you would manage a remote team effectively.', 'Management', 'short_answer', 300);

-- Long Answer Questions (2 questions) - Same structure as short answer
INSERT INTO quiz_questions (id, question, category, type, max_length) VALUES
(49, 'Imagine sales have dropped 25% in 3 months. Walk me through your step-by-step plan to identify the root cause and turn the business around.', 'Strategic Thinking', 'long_answer', 1000),
(50, 'You''re tasked with building an operations team from scratch in India to support a US-based business. Describe in detail how you would recruit, train, and scale this team while ensuring alignment with US time zones and client expectations.', 'Operations', 'long_answer', 1000);